name = 'xukainan '
print(name.title())
print("hello" + name)
print("hello\n" + name)
print("hello\t" + name)
print(name.upper())
print(name.lower())
print(name.rstrip())
print(name.lstrip())
print(name.strip())